aca_shop_home:
    path:     /
    defaults: { _controller: AcaShopBundle:Home:index }

# They need to have a unique name
aca_shop_login:
    path:     /login_user
    defaults: { _controller: AcaShopBundle:Home:login }

aca_shop_logout:
    path:     /logout
    defaults: { _controller: AcaShopBundle:Home:logout }

aca_shop_products:
    path:     /products
    defaults: { _controller: AcaShopBundle:Product:show }

aca_shop_addcart:
    path:     /add_cart
    defaults: { _controller: AcaShopBundle:Cart:add }