aca_shop_home:
    path:     /
    defaults: { _controller: AcaShopBundle:Home:index }

# They need to have a unique name
aca_shop_login:
    path:     /login_user
    defaults: { _controller: AcaShopBundle:Home:login }

aca_shop_logout:
    path:     /logout
    defaults: { _controller: AcaShopBundle:Home:logout }

aca_shop_products:
    path:     /products
    defaults: { _controller: AcaShopBundle:Product:show }

aca_shop_addcart:
    path:     /add_cart
    defaults: { _controller: AcaShopBundle:Cart:add }

aca_shop_cart:
    path:     /cart
    defaults: { _controller: AcaShopBundle:Cart:display }

aca_shop_remove:
    path:     /remove_cart_item
    defaults: { _controller: AcaShopBundle:Cart:remove }

aca_shop_update:
    path:     /update_cart
    defaults: { _controller: AcaShopBundle:Cart:update }

aca_shop_delete:
    path:     /delete_cart_item
    defaults: { _controller: AcaShopBundle:Cart:delete }

aca_shop_signup:
    path:     /sign_up
    defaults: { _controller: AcaShopBundle:Signup:sign }

aca_shop_signon:
    path:     /sign_on
    defaults: { _controller: AcaShopBundle:Signup:proceed }

aca_shipping_address:
    path: /shipping_address
    defaults: { _controller: AcaShopBundle:Cart:shippingAddress }

aca_place_order:
    path: /place_order
    defaults: { _controller: AcaShopBundle:Order:place }

aca_place_receipt:
    path: /receipt
    defaults: { _controller: AcaShopBundle:Receipt:show }