aca_shop_home:
    path:     /
    defaults: { _controller: AcaShopBundle:Home:index }

# you can comment with a pound sign
aca_shop_login:
    path:     /login_user
    defaults: { _controller: AcaShopBundle:Home:login }

aca_shop_logout:
    path:     /logout
    defaults: { _controller: AcaShopBundle:Home:logout }
