services:
#    aca_shop.example:
#        class: Aca\Bundle\ShopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    aca.db:
        class: Aca\Bundle\ShopBundle\Db\DBCommon
        arguments: [%database_host%, %database_user%, %database_password%, %database_name%]

    aca.cart:
        class: Aca\Bundle\ShopBundle\Shop\Cart
        arguments: [@aca.db, @session, @aca.product]

    aca.order:
        class: Aca\Bundle\ShopBundle\Shop\OrderComplete
        arguments: [@aca.db, @session]

    aca.product:
        class: Aca\Bundle\ShopBundle\Shop\Product
        arguments: [@aca.db]

    aca.user:
        class: Aca\Bundle\ShopBundle\Shop\User
        arguments: [@aca.db, @session]



