services:
#    aca_shop.example:
#        class: Aca\Bundle\ShopBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    aca.db:
        class: Aca\Bundle\ShopBundle\Db\DBCommon
        arguments: [%database_host%, %database_user%, %database_password%, %database_name%]

